-- Archivo SQL para insertar datos semilla en la tabla de usuarios (Users), productos (Products), clientes (Clientes), empleados (Empleados)
-- SQLite utiliza por defecto el nombre en plural generado por Sequelize

INSERT INTO "ListaPrecios" (nombre, createdAt, updatedAt) VALUES
('Lista 1', datetime('now'), datetime('now')),
('Lista 2', datetime('now'), datetime('now')),
('Lista 3', datetime('now'), datetime('now')),
('Lista 4', datetime('now'), datetime('now')),
('Lista 5', datetime('now'), datetime('now')),
('Lista 6', datetime('now'), datetime('now')),
('Lista 7', datetime('now'), datetime('now')),
('Lista 8', datetime('now'), datetime('now'));

INSERT INTO "Users" (nombre, createdAt, updatedAt) VALUES
('Juan Pérez', datetime('now'), datetime('now')),
('María Rodríguez', datetime('now'), datetime('now')),
('Carlos Gómez', datetime('now'), datetime('now')),
('Ana Martínez', datetime('now'), datetime('now')),
('Lucía Fernández', datetime('now'), datetime('now'));

INSERT INTO "Clientes" (nombre, direccion, contacto, listaPreciosId, createdAt, updatedAt) VALUES
('Supermercado Alborada', 'Av. Rivadavia 1234', '11-4567-8901', 1, datetime('now'), datetime('now')),
('MiniMarket Express', 'Calle Corrientes 567', '11-2345-6789', 2, datetime('now'), datetime('now')),
('Almacén de Don Pepe', 'Belgrano 890', '11-9876-5432', 1, datetime('now'), datetime('now'));

INSERT INTO "Marcas" (nombre, createdAt, updatedAt) VALUES
('Marlboro', datetime('now'), datetime('now')),
('Lucky Strike (Lucky)', datetime('now'), datetime('now')),
('Philip Morris (Philip)', datetime('now'), datetime('now')),
('Chesterfield', datetime('now'), datetime('now')),
('Camel', datetime('now'), datetime('now')),
('Red Point', datetime('now'), datetime('now')),
('Milenio / Mill', datetime('now'), datetime('now')),
('Melbourne (Melbo)', datetime('now'), datetime('now')),
('Kiel', datetime('now'), datetime('now')),
('Master', datetime('now'), datetime('now')),
('OCB', datetime('now'), datetime('now')),
('Zeus', datetime('now'), datetime('now')),
('Bic', datetime('now'), datetime('now')),
('Gillette', datetime('now'), datetime('now')),
('Otras Marcas de Cigarrillos y Tabaco', datetime('now'), datetime('now')),
('Otras Marcas de Varios', datetime('now'), datetime('now')),
('Productos Genéricos', datetime('now'), datetime('now'));

INSERT INTO "Products" (nombre, marcaId, costo, createdAt, updatedAt) VALUES
('MARLB. CRAFTED BOX (todos)', 1, 0.00, datetime('now'), datetime('now')),
('MARLB. CRAFTED COMUN (todos)', 1, 0.00, datetime('now'), datetime('now')),
('MARLBORO 12', 1, 0.00, datetime('now'), datetime('now')),
('MARLBORO BOX 20', 1, 0.00, datetime('now'), datetime('now')),
('MARLBORO COMUN 20', 1, 0.00, datetime('now'), datetime('now')),
('MARLBORO FUSION 12', 1, 0.00, datetime('now'), datetime('now')),
('MARLBORO FUSIÓN BOX 20', 1, 0.00, datetime('now'), datetime('now')),
('MARLBORO GOLD BOX 20', 1, 0.00, datetime('now'), datetime('now')),
('MARLBORO ICE BLAST BOX 20', 1, 0.00, datetime('now'), datetime('now')),
('MARLBORO SUMMER BOX 20', 1, 0.00, datetime('now'), datetime('now')),
('LUCKY BLANCO 12', 2, 0.00, datetime('now'), datetime('now')),
('LUCKY BLANCO BOX 20', 2, 0.00, datetime('now'), datetime('now')),
('LUCKY BLANCO COMUN 20', 2, 0.00, datetime('now'), datetime('now')),
('LUCKY CONV. COMÚN 20', 2, 0.00, datetime('now'), datetime('now')),
('LUCKY CONVERTIBLE 12', 2, 0.00, datetime('now'), datetime('now')),
('LUCKY CONVERTIBLE BOX 20', 2, 0.00, datetime('now'), datetime('now')),
('LUCKY DOBLE PLUS 12', 2, 0.00, datetime('now'), datetime('now')),
('LUCKY DOBLE PLUS BOX 20', 2, 0.00, datetime('now'), datetime('now')),
('LUCKY ECONÓMICO (rojo)', 2, 0.00, datetime('now'), datetime('now')),
('LUCKY ORIGEN CLICK BOX', 2, 0.00, datetime('now'), datetime('now')),
('LUCKY ORIGEN CLICK DE 10', 2, 0.00, datetime('now'), datetime('now')),
('LUCKY ORIGEN CLICK KS 20', 2, 0.00, datetime('now'), datetime('now')),
('LUCKY ORIGEN RED BOX 20', 2, 0.00, datetime('now'), datetime('now')),
('LUCKY ORIGEN RED DE 10', 2, 0.00, datetime('now'), datetime('now')),
('LUCKY ORIGEN RED KS. 20', 2, 0.00, datetime('now'), datetime('now')),
('LUCKY PARISIENES BOX 20', 2, 0.00, datetime('now'), datetime('now')),
('LUCKY RED MIX 12', 2, 0.00, datetime('now'), datetime('now')),
('LUCKY RED MIX BOX 20/ UVA XL', 2, 0.00, datetime('now'), datetime('now')),
('LUCKY SILVER (PALL MALL) 20', 2, 0.00, datetime('now'), datetime('now')),
('TAB. LUCKY GALPAO', 2, 0.00, datetime('now'), datetime('now')),
('TAB. LUCKY GOLDEN', 2, 0.00, datetime('now'), datetime('now')),
('TAB. LUCKY ORIGINAL', 2, 0.00, datetime('now'), datetime('now')),
('PHILIP MORRIS 12', 3, 0.00, datetime('now'), datetime('now')),
('PHILIP MORRIS BOX 20', 3, 0.00, datetime('now'), datetime('now')),
('PHILIP MORRIS CAPS 12', 3, 0.00, datetime('now'), datetime('now')),
('PHILIP MORRIS CAPS BOX 20', 3, 0.00, datetime('now'), datetime('now')),
('PHILIP MORRIS COMUN 20', 3, 0.00, datetime('now'), datetime('now')),
('PHILIP SELECT KS 20', 3, 0.00, datetime('now'), datetime('now')),
('CHESTERFIELD 12', 4, 0.00, datetime('now'), datetime('now')),
('CHESTERFIELD COMUN 20', 4, 0.00, datetime('now'), datetime('now')),
('CHESTERFIELD FRESH 10', 4, 0.00, datetime('now'), datetime('now')),
('CHESTERFIELD FRESH BOX 20', 4, 0.00, datetime('now'), datetime('now')),
('CHESTERFIELD FRESH COMUN', 4, 0.00, datetime('now'), datetime('now')),
('CHESTERFIELD REMIX BOX 20', 4, 0.00, datetime('now'), datetime('now')),
('CAMEL 11', 5, 0.00, datetime('now'), datetime('now')),
('CAMEL BOX 20', 5, 0.00, datetime('now'), datetime('now')),
('CAMEL KS. 20', 5, 0.00, datetime('now'), datetime('now')),
('CAMEL LEGEND BOX 20', 5, 0.00, datetime('now'), datetime('now')),
('RED POINT BOX 20', 6, 0.00, datetime('now'), datetime('now')),
('RED POINT CLICK BOX 20', 6, 0.00, datetime('now'), datetime('now')),
('RED POINT COMUN', 6, 0.00, datetime('now'), datetime('now')),
('RED POINT DE 10', 6, 0.00, datetime('now'), datetime('now')),
('RED POINT MENTOLADO', 6, 0.00, datetime('now'), datetime('now')),
('MILENIO CLICK BOX', 7, 0.00, datetime('now'), datetime('now')),
('MILENIO VID ICERGY (uva/mentm)', 7, 0.00, datetime('now'), datetime('now')),
('MILL CAPSULA BOX', 7, 0.00, datetime('now'), datetime('now')),
('MILL KS 20', 7, 0.00, datetime('now'), datetime('now')),
('MELBO COMUN DE 20/SUAVE/MENTOL', 8, 0.00, datetime('now'), datetime('now')),
('MELBOURNE KS rojo/verde/dorado', 8, 0.00, datetime('now'), datetime('now')),
('KIEL BOX 20', 9, 0.00, datetime('now'), datetime('now')),
('KIEL COMUN 20', 9, 0.00, datetime('now'), datetime('now')),
('MASTER BOX', 10, 0.00, datetime('now'), datetime('now')),
('MASTER COMUN 20', 10, 0.00, datetime('now'), datetime('now')),
('FILTROS OCB REGULAR', 11, 0.00, datetime('now'), datetime('now')),
('FILTROS OCB SLIM', 11, 0.00, datetime('now'), datetime('now')),
('PAPELILLO OCB NEGRO X25', 11, 0.00, datetime('now'), datetime('now')),
('CELULOSA ZEUS X 25', 12, 0.00, datetime('now'), datetime('now')),
('CELULOSA ZEUS X LIBRITO', 12, 0.00, datetime('now'), datetime('now')),
('ENCENDEDOR MAXI BIC UN.', 13, 0.00, datetime('now'), datetime('now')),
('ENCENDEDOR MINI BIC UN.', 13, 0.00, datetime('now'), datetime('now')),
('GILLETTE 2 FILOS', 14, 0.00, datetime('now'), datetime('now')),
('GILLETTE 3 FILOS', 14, 0.00, datetime('now'), datetime('now')),
('43/70 LARGO BOX 20', 15, 0.00, datetime('now'), datetime('now')),
('BOLD KS 20', 15, 0.00, datetime('now'), datetime('now')),
('DOLCHESTER DORADO BOX', 15, 0.00, datetime('now'), datetime('now')),
('GO COMÚN 20', 15, 0.00, datetime('now'), datetime('now')),
('HARMONY', 15, 0.00, datetime('now'), datetime('now')),
('PARLIAMENT BOX 20', 15, 0.00, datetime('now'), datetime('now')),
('PIER BIX', 15, 0.00, datetime('now'), datetime('now')),
('TAB. 4 LEGUAS X60G.', 15, 0.00, datetime('now'), datetime('now')),
('TAB. CERRITO ORIGINAL/VAINILLA', 15, 0.00, datetime('now'), datetime('now')),
('TAB. LAS HOJAS X59G.', 15, 0.00, datetime('now'), datetime('now')),
('VIRGINIA SLIM', 15, 0.00, datetime('now'), datetime('now')),
('AFEITADORA FLEXOR 2 FILOS', 16, 0.00, datetime('now'), datetime('now')),
('ENCENDEDOR CANDELA X 25U', 16, 0.00, datetime('now'), datetime('now')),
('ENCENDEDOR CATALÍTICO LEON X 50', 16, 0.00, datetime('now'), datetime('now')),
('ENCENDEDORE CRICKET X5', 16, 0.00, datetime('now'), datetime('now')),
('OFF FAMILIAR NARANJA', 16, 0.00, datetime('now'), datetime('now')),
('PILAS ENERGIZER AA /AAA', 16, 0.00, datetime('now'), datetime('now')),
('ENCENDEDOR econ. X25', 17, 0.00, datetime('now'), datetime('now')),
('ENCENDEDOR econom. X 50 UN.', 17, 0.00, datetime('now'), datetime('now')),
('GOMITAS X 30 (VARIOS MOTIVOS)', 17, 0.00, datetime('now'), datetime('now')),
('Pitillos XL', 17, 0.00, datetime('now'), datetime('now'));

INSERT INTO "Prices" (precio, productId, listaPreciosId, createdAt, updatedAt) VALUES
(15.00, 1, 1, datetime('now'), datetime('now')),
(15.00, 2, 1, datetime('now'), datetime('now')),
(15.00, 3, 1, datetime('now'), datetime('now')),
(15.00, 4, 1, datetime('now'), datetime('now')),
(15.00, 5, 1, datetime('now'), datetime('now')),
(15.00, 6, 1, datetime('now'), datetime('now')),
(15.00, 7, 1, datetime('now'), datetime('now')),
(15.00, 8, 1, datetime('now'), datetime('now')),
(15.00, 9, 1, datetime('now'), datetime('now')),
(15.00, 10, 1, datetime('now'), datetime('now')),
(20.00, 11, 1, datetime('now'), datetime('now')),
(25.00, 11, 2, datetime('now'), datetime('now')),
(30.00, 11, 3, datetime('now'), datetime('now')),
(35.00, 11, 4, datetime('now'), datetime('now')),
(20.00, 12, 1, datetime('now'), datetime('now')),
(25.00, 12, 2, datetime('now'), datetime('now')),
(30.00, 12, 3, datetime('now'), datetime('now')),
(35.00, 12, 4, datetime('now'), datetime('now')),
(20.00, 13, 1, datetime('now'), datetime('now')),
(25.00, 13, 2, datetime('now'), datetime('now')),
(30.00, 13, 3, datetime('now'), datetime('now')),
(35.00, 13, 4, datetime('now'), datetime('now')),
(20.00, 14, 1, datetime('now'), datetime('now')),
(25.00, 14, 2, datetime('now'), datetime('now')),
(30.00, 14, 3, datetime('now'), datetime('now')),
(35.00, 14, 4, datetime('now'), datetime('now')),
(20.00, 15, 1, datetime('now'), datetime('now')),
(25.00, 15, 2, datetime('now'), datetime('now')),
(30.00, 15, 3, datetime('now'), datetime('now')),
(35.00, 15, 4, datetime('now'), datetime('now')),
(20.00, 16, 1, datetime('now'), datetime('now')),
(25.00, 16, 2, datetime('now'), datetime('now')),
(30.00, 16, 3, datetime('now'), datetime('now')),
(35.00, 16, 4, datetime('now'), datetime('now')),
(20.00, 17, 1, datetime('now'), datetime('now')),
(25.00, 17, 2, datetime('now'), datetime('now')),
(30.00, 17, 3, datetime('now'), datetime('now')),
(35.00, 17, 4, datetime('now'), datetime('now')),
(20.00, 18, 1, datetime('now'), datetime('now')),
(25.00, 18, 2, datetime('now'), datetime('now')),
(30.00, 18, 3, datetime('now'), datetime('now')),
(35.00, 18, 4, datetime('now'), datetime('now')),
(20.00, 19, 1, datetime('now'), datetime('now')),
(25.00, 19, 2, datetime('now'), datetime('now')),
(30.00, 19, 3, datetime('now'), datetime('now')),
(35.00, 19, 4, datetime('now'), datetime('now')),
(20.00, 20, 1, datetime('now'), datetime('now')),
(25.00, 20, 2, datetime('now'), datetime('now')),
(30.00, 20, 3, datetime('now'), datetime('now')),
(35.00, 20, 4, datetime('now'), datetime('now')),
(20.00, 21, 1, datetime('now'), datetime('now')),
(25.00, 21, 2, datetime('now'), datetime('now')),
(30.00, 21, 3, datetime('now'), datetime('now')),
(35.00, 21, 4, datetime('now'), datetime('now')),
(20.00, 22, 1, datetime('now'), datetime('now')),
(25.00, 22, 2, datetime('now'), datetime('now')),
(30.00, 22, 3, datetime('now'), datetime('now')),
(35.00, 22, 4, datetime('now'), datetime('now')),
(20.00, 23, 1, datetime('now'), datetime('now')),
(25.00, 23, 2, datetime('now'), datetime('now')),
(30.00, 23, 3, datetime('now'), datetime('now')),
(35.00, 23, 4, datetime('now'), datetime('now')),
(20.00, 24, 1, datetime('now'), datetime('now')),
(25.00, 24, 2, datetime('now'), datetime('now')),
(30.00, 24, 3, datetime('now'), datetime('now')),
(35.00, 24, 4, datetime('now'), datetime('now')),
(20.00, 25, 1, datetime('now'), datetime('now')),
(25.00, 25, 2, datetime('now'), datetime('now')),
(30.00, 25, 3, datetime('now'), datetime('now')),
(35.00, 25, 4, datetime('now'), datetime('now')),
(20.00, 26, 1, datetime('now'), datetime('now')),
(25.00, 26, 2, datetime('now'), datetime('now')),
(30.00, 26, 3, datetime('now'), datetime('now')),
(35.00, 26, 4, datetime('now'), datetime('now')),
(20.00, 27, 1, datetime('now'), datetime('now')),
(25.00, 27, 2, datetime('now'), datetime('now')),
(30.00, 27, 3, datetime('now'), datetime('now')),
(35.00, 27, 4, datetime('now'), datetime('now')),
(20.00, 28, 1, datetime('now'), datetime('now')),
(25.00, 28, 2, datetime('now'), datetime('now')),
(30.00, 28, 3, datetime('now'), datetime('now')),
(35.00, 28, 4, datetime('now'), datetime('now')),
(20.00, 29, 1, datetime('now'), datetime('now')),
(25.00, 29, 2, datetime('now'), datetime('now')),
(30.00, 29, 3, datetime('now'), datetime('now')),
(35.00, 29, 4, datetime('now'), datetime('now')),
(20.00, 30, 1, datetime('now'), datetime('now')),
(25.00, 30, 2, datetime('now'), datetime('now')),
(30.00, 30, 3, datetime('now'), datetime('now')),
(35.00, 30, 4, datetime('now'), datetime('now')),
(20.00, 31, 1, datetime('now'), datetime('now')),
(25.00, 31, 2, datetime('now'), datetime('now')),
(30.00, 31, 3, datetime('now'), datetime('now')),
(35.00, 31, 4, datetime('now'), datetime('now')),
(20.00, 32, 1, datetime('now'), datetime('now')),
(25.00, 32, 2, datetime('now'), datetime('now')),
(30.00, 32, 3, datetime('now'), datetime('now')),
(35.00, 32, 4, datetime('now'), datetime('now')),
(40.00, 49, 1, datetime('now'), datetime('now')),
(45.00, 49, 2, datetime('now'), datetime('now')),
(50.00, 49, 3, datetime('now'), datetime('now')),
(40.00, 50, 1, datetime('now'), datetime('now')),
(45.00, 50, 2, datetime('now'), datetime('now')),
(50.00, 50, 3, datetime('now'), datetime('now')),
(40.00, 51, 1, datetime('now'), datetime('now')),
(45.00, 51, 2, datetime('now'), datetime('now')),
(50.00, 51, 3, datetime('now'), datetime('now')),
(40.00, 52, 1, datetime('now'), datetime('now')),
(45.00, 52, 2, datetime('now'), datetime('now')),
(50.00, 52, 3, datetime('now'), datetime('now')),
(40.00, 53, 1, datetime('now'), datetime('now')),
(45.00, 53, 2, datetime('now'), datetime('now')),
(50.00, 53, 3, datetime('now'), datetime('now'));

INSERT INTO "Empleados" (nombre, apellido, active, createdAt, updatedAt) VALUES 
('Martín', 'Gómez', 1, datetime('now'), datetime('now')), 
('Florencia', 'Díaz', 1, datetime('now'), datetime('now')), 
('Roberto', 'Sánchez', 1, datetime('now'), datetime('now'));

INSERT INTO "Ventas" (fecha_emision, total, ganancia, active, empleadoId, clienteId, createdAt, updatedAt) VALUES
(datetime('now', '-2 days'), 235.00, 235.00, 1, 1, 1, datetime('now'), datetime('now')),
(datetime('now', '-1 days'), 265.00, 265.00, 1, 2, 2, datetime('now'), datetime('now')),
(datetime('now'), 750.00, 750.00, 1, 1, 3, datetime('now'), datetime('now')),
(datetime('now'), 145.00, 145.00, 1, 2, 1, datetime('now'), datetime('now')),
(datetime('now'), 290.00, 290.00, 1, 3, 2, datetime('now'), datetime('now'));

INSERT INTO "Detalles" (sellId, productId, priceId, cantidad, precio, createdAt, updatedAt) VALUES
(1, 3, 3, 5, 15.00, datetime('now'), datetime('now')),
(1, 11, 11, 4, 20.00, datetime('now'), datetime('now')),
(1, 49, 99, 2, 40.00, datetime('now'), datetime('now')),
(2, 3, 3, 2, 15.00, datetime('now'), datetime('now')),
(2, 11, 12, 4, 25.00, datetime('now'), datetime('now')),
(2, 49, 100, 3, 45.00, datetime('now'), datetime('now')),
(3, 4, 4, 10, 15.00, datetime('now'), datetime('now')),
(3, 12, 15, 10, 20.00, datetime('now'), datetime('now')),
(3, 50, 102, 10, 40.00, datetime('now'), datetime('now')),
(4, 8, 8, 3, 15.00, datetime('now'), datetime('now')),
(4, 25, 67, 5, 20.00, datetime('now'), datetime('now')),
(5, 25, 68, 8, 25.00, datetime('now'), datetime('now')),
(5, 53, 112, 2, 45.00, datetime('now'), datetime('now'));
